name: Deploy Python App to EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Get EC2 Public IP
        id: get_ip
        run: echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
        working-directory: terraform

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy Python App to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_IP }} << 'EOF'
          sudo apt update && sudo apt install -y python3-pip
          git clone https://github.com/${GITHUB_REPOSITORY}.git || (cd $(basename $GITHUB_REPOSITORY) && git pull)
          cd $(basename $GITHUB_REPOSITORY)
          pip3 install -r requirements.txt
          nohup python3 app.py > app.log 2>&1 &
          EOF
